# Base
version: '2'

services:

  zookeeper-base:
    image: hyperledger/fabric-zookeeper
    environment:
      - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888
    ports:
      - 2181
      - 2888
      - 3888

  kafka-base:
    image: hyperledger/fabric-kafka
    environment:
      - KAFKA_LOG_RETENTION_MS=-1
      - KAFKA_MESSAGE_MAX_BYTES=103809024
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - KAFKA_DEFAULT_REPLICATION_FACTOR=4
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
    ports:
      - 9092
   
  orderer-base:
    image: hyperledger/fabric-orderer
    environment:
      # Orderer
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/config/genesis.block
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/crypto/orderer/msp
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LEDGERTYPE=file
      - ORDERER_GENERAL_BATCHTIMEOUT=1s
      - ORDERER_GENERAL_MAXMESSAGECOUNT=10
      - ORDERER_GENERAL_MAXWINDOWSIZE=1000
      # Orderer TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/crypto/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/crypto/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/crypto/orderer/tls/ca.crt, /etc/hyperledger/crypto/orgaustria/peer/tls/ca.crt, /etc/hyperledger/crypto/orggermany/peer/tls/ca.crt, /etc/hyperledger/crypto/orgitaly/peer/tls/ca.crt, /etc/hyperledger/crypto/orgnetherlands/peer/tls/ca.crt]
      # Kafka
      - ORDERER_KAFKA_VERSION=0.9.0.1
      - ORDERER_KAFKA_RETRY_SHORTINTERVAL=1s
      - ORDERER_KAFKA_RETRY_SHORTTOTAL=30s
      - ORDERER_KAFKA_VERBOSE=true
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderers
    command: orderer
    volumes:
      - ./../../artifactsKafka/orderer:/etc/hyperledger/config
      - ./../../artifactsKafka/crypto-config/peerOrganizations/orgaustria.dltrouting.com/peers/peer0.orgaustria.dltrouting.com/:/etc/hyperledger/crypto/orgaustria/peer
      - ./../../artifactsKafka/crypto-config/peerOrganizations/orggermany.dltrouting.com/peers/peer0.orggermany.dltrouting.com/:/etc/hyperledger/crypto/orggermany/peer
      - ./../../artifactsKafka/crypto-config/peerOrganizations/orgitaly.dltrouting.com/peers/peer0.orgitaly.dltrouting.com/:/etc/hyperledger/crypto/orgitaly/peer
      - ./../../artifactsKafka/crypto-config/peerOrganizations/orgnetherlands.dltrouting.com/peers/peer0.orgnetherlands.dltrouting.com/:/etc/hyperledger/crypto/orgnetherlands/peer
    extra_hosts:
      - "host.orgaustria.dltrouting.com:<<austria_ip>>"
      - "host.orggermany.dltrouting.com:<<germany_ip>>"
      - "host.orgitaly.dltrouting.com:<<italy_ip>>"
      - "host.orgnetherlands.dltrouting.com:<<netherlands_ip>>"

  ca-base:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_TLS_ENABLED=true
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    extra_hosts:
      - "host.orgaustria.dltrouting.com:<<austria_ip>>"
      - "host.orggermany.dltrouting.com:<<germany_ip>>"
      - "host.orgitaly.dltrouting.com:<<italy_ip>>"
      - "host.orgnetherlands.dltrouting.com:<<netherlands_ip>>"

  peer-base:
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=docker_dltroutingnetwork
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      # The following setting skips the gossip handshake since we are
      # are not doing mutual TLS
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
    extra_hosts:
      - "host.orgaustria.dltrouting.com:<<austria_ip>>"
      - "host.orggermany.dltrouting.com:<<germany_ip>>"
      - "host.orgitaly.dltrouting.com:<<italy_ip>>"
      - "host.orgnetherlands.dltrouting.com:<<netherlands_ip>>"
      
  cli-base:
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GO_PATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/admin/msp
      - ORDERER_CA_FILE=/etc/hyperledger/crypto/orderer/msp/tlscacerts/tlsca.dltrouting.com-cert.pem
      - CHANNEL_TX_FILE=/etc/hyperledger/channel/channel.tx
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    volumes:
      - /var/run/:/host/var/run/
      - ./../../artifactsKafka/channel/:/etc/hyperledger/channel
      - ./../../scripts/cli-peer/:/opt/gopath/src/github.com/hyperledger/fabric/peer
      - ./../../src/chaincode/:/opt/gopath/src/github.com/hyperledger/fabric/chaincode
    extra_hosts:
      - "host.orgaustria.dltrouting.com:<<austria_ip>>"
      - "host.orggermany.dltrouting.com:<<germany_ip>>"
      - "host.orgitaly.dltrouting.com:<<italy_ip>>"
      - "host.orgnetherlands.dltrouting.com:<<netherlands_ip>>"
