# Orderer
version: '2'

services:

  zookeeper0:
    extends:
        file: docker-base.yaml
        service: zookeeper-base
    container_name: zookeeper0
    environment:
        - ZOO_MY_ID=1

  zookeeper1:
      extends:
          file: docker-base.yaml
          service: zookeeper-base
      container_name: zookeeper1
      environment:
          - ZOO_MY_ID=2

  zookeeper2:
      extends:
          file: docker-base.yaml
          service: zookeeper-base
      container_name: zookeeper2
      environment:
          - ZOO_MY_ID=3

  kafka0:
      extends:
          file: docker-base.yaml
          service: kafka-base
      container_name: kafka0
      environment:
          - KAFKA_BROKER_ID=0

  kafka1:
      extends:
          file: docker-base.yaml
          service: kafka-base
      container_name: kafka1
      environment:
          - KAFKA_BROKER_ID=1

  kafka2:
      extends:
          file: docker-base.yaml
          service: kafka-base
      container_name: kafka2
      environment:
          - KAFKA_BROKER_ID=2

  kafka3:
      extends:
          file: docker-base.yaml
          service: kafka-base
      container_name: kafka3
      environment:
          - KAFKA_BROKER_ID=3