# Organisation 1
version: '2'

services:

  # CA
  ca.orgaustria.dltrouting.com:
    container_name: ca.orgaustria.dltrouting.com
    extends:
      file: docker-base.yaml
      service: ca-base
    environment:
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.orgaustria.dltrouting.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/d2c2c6bc2edbb7f01ae5a2148fa573437a234dc87249ea7761e7575b69e7c414_sk
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.orgaustria.dltrouting.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/d2c2c6bc2edbb7f01ae5a2148fa573437a234dc87249ea7761e7575b69e7c414_sk
    ports:
      - 7054:7054
    volumes:
      - ./../../artifactsSolo/crypto-config/peerOrganizations/orgaustria.dltrouting.com/ca/:/etc/hyperledger/fabric-ca-server-config
  
  # Peer 0
  peer0.orgaustria.dltrouting.com:
    container_name: peer0.orgaustria.dltrouting.com
    extends:
      file: docker-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.orgaustria.dltrouting.com
      - CORE_PEER_LOCALMSPID=OrgAustriaMSP
      - CORE_PEER_ADDRESS=peer0.orgaustria.dltrouting.com:7051
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer0.orgaustria.dltrouting.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
      - ./../../artifactsSolo/crypto-config/peerOrganizations/orgaustria.dltrouting.com/peers/peer0.orgaustria.dltrouting.com/:/etc/hyperledger/crypto/peer

  couchdb.peer0.orgaustria.dltrouting.com:
    image: hyperledger/fabric-couchdb
    container_name: couchdb.peer0.orgaustria.dltrouting.com
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 7984:5984

  cli.peer0.orgaustria.dltrouting.com:
    container_name: cli.peer0.orgaustria.dltrouting.com
    extends:
      file: docker-base.yaml
      service: cli-base
    environment:
      - CORE_PEER_ID=cli.peer0.orgaustria.dltrouting.com
      - CORE_PEER_ADDRESS=peer0.orgaustria.dltrouting.com:7051
      - CORE_PEER_LOCALMSPID=OrgAustriaMSP
      - ORDERER_ADDRESS=host.orgaustria.dltrouting.com:7050
    volumes:
      - ./../../artifactsSolo/crypto-config/peerOrganizations/orgaustria.dltrouting.com/peers/peer0.orgaustria.dltrouting.com/:/etc/hyperledger/crypto/peer
      - ./../../artifactsSolo/crypto-config/peerOrganizations/orgaustria.dltrouting.com/users/Admin@orgaustria.dltrouting.com/msp/:/etc/hyperledger/crypto/admin/msp
      - ./../../artifactsSolo/crypto-config/ordererOrganizations/dltrouting.com/orderers/host.orgaustria.dltrouting.com/msp/tlscacerts:/etc/hyperledger/crypto/orderer/msp/tlscacerts
